MovieWeb/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Database.Design;
using MovieWeb.Domain;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomerController : Controller
    {
        private IMovieDatabase _context;


        public CustomerController(IMovieDatabase context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));

        }
        public IActionResult Index()
        {
            List<CustomerListViewModel> Customers = new List<CustomerListViewModel>();

            foreach (var Customer in _context.GetCustomer())
            {
                Customers.Add(new CustomerListViewModel() { CustomerId = Customer.CustomerId, Naam = Customer.Naam, Voornaam = Customer.Voornaam });
            }
            return View(Customers);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CustomerCreateViewModel customerCreateViewModel)
        {           
            var isModelValid = TryValidateModel(customerCreateViewModel);

            if (isModelValid)
            {
                var newEntity = new Customer
                {
                    CustomerId = customerCreateViewModel.CustomerId,
                    Naam = customerCreateViewModel.Naam,
                    Voornaam = customerCreateViewModel.Voornaam

                };
                
                _context.AddCustomer(newEntity);

                return RedirectToAction("Index");
            }
            return View(customerCreateViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var customerCreateViewModel = new CustomerCreateViewModel();

            return View(customerCreateViewModel);
        }


        [HttpGet]
        public IActionResult Detail(Guid CustomerId)
        {         
            var selectedCustomer = _context.FindCustomerById(CustomerId);
            CustomerDetailViewModel viewCustomer = new CustomerDetailViewModel()
            {
                Naam = selectedCustomer.Naam,
                Voornaam = selectedCustomer.Voornaam,
            };
            return View(viewCustomer);
        }


        [HttpGet]
        public IActionResult Edit(Guid CustomerId)
        {
            var selectedCustomer = _context.FindCustomerById(CustomerId);

            if (selectedCustomer == null) return new NotFoundResult();

            var newCustomerEdit = new CustomerEditViewModel()
            {
                Naam = selectedCustomer.Naam,
                Voornaam = selectedCustomer.Voornaam,
            };

            return View(newCustomerEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid Id, [FromForm] CustomerEditViewModel newCustomerEdit)
        {
            var selectedCustomer = _context.FindCustomerById(newCustomerEdit.CustomerId);

            if (selectedCustomer == null) return new NotFoundResult();

            selectedCustomer.Naam = newCustomerEdit.Naam;
            selectedCustomer.Voornaam = newCustomerEdit.Voornaam;

            _context.UpdateCustomer(selectedCustomer);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(Guid customerId)
        {
            var selectedCustomer = _context.FindCustomerById(customerId);

            var newCustomerDelete = new CustomerDeleteViewModel()
            {
                CustomerId = selectedCustomer.CustomerId,
                Naam = selectedCustomer.Naam,
                
            };

            return View(newCustomerDelete);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(CustomerDeleteViewModel newCustomerDelete)
        {            
            var selectedCustomer = _context.FindCustomerById(newCustomerDelete.CustomerId);

            if (selectedCustomer == null) return new NotFoundResult();

            _context.RemoveCustomer(selectedCustomer);

            return RedirectToAction("Index");
        }
    }
}

MovieWeb/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Database;
using MovieWeb.Database.Design;
using MovieWeb.Domain;
using MovieWeb.Models;
using SpelenMetBlazor.Data;

namespace MovieWeb.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class MovieController : Controller
    {
        private IMovieDatabase _myDatabase;

        private static List<Movie> movieEntities = new List<Movie>();
        
        private static List<MovieImg> movieImgEntities = new List<MovieImg>();

        private static MovieImg ImgToUpload;

        public static int Filter = 0;

        public static string Search = "";

        public static List<ExampleModel> mylist;
   
        public MovieController(IMovieDatabase mydatabase)
        {
            _myDatabase = mydatabase;
            movieEntities = _myDatabase.GetMovies();
            movieImgEntities = _myDatabase.GetMovieImg();          
        }
                      
        [HttpGet]        
        public IActionResult Index()
        {
            List<Movie> mylist;
            var movieViewModels = new List<MovieListViewModel>();                     
            if (Search != "")
            {   
                    movieEntities = movieEntities.FindAll(x => x.Tittel.Contains($"{Search}"));
                Search = "";
            }
            switch (Filter)
            {
                case 1:
                    mylist = movieEntities.OrderByDescending(x => x.Tittel).ToList();
                    break;
                case 2:
                    mylist = movieEntities.OrderByDescending(x => x.Release).ToList();
                    break;
                case 3:
                    mylist = movieEntities.OrderBy(x => x.Release).ToList();
                    break;
                default:
                    mylist = movieEntities.OrderBy(x => x.Tittel).ToList();
                    break;

            }
            foreach (Movie movie in mylist)
            {
                movieViewModels.Add(new MovieListViewModel() { MovieId = movie.MovieId, Duurtijd = movie.Duurtijd, Tittel = movie.Tittel, MovieImg = movie.MovieImg, Release = movie.Release });
            }
            return View(movieViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var movieCreateViewModel = new MovieCreateViewModel();
            if (ImgToUpload != null)
            {
                movieCreateViewModel.MovieImg = ImgToUpload;               
            }

            return View(movieCreateViewModel);
        }
        [HttpGet]
        public IActionResult DeleteImg(MovieImg myimage)
        {
            movieImgEntities.Clear();
            return RedirectToAction("Create");
        }
        
        [AutoValidateAntiforgeryToken]
        [HttpPost]       
        public IActionResult Create(MovieCreateViewModel movieViewModel)
        {
            var isValid = TryValidateModel(movieViewModel);
            
            if (isValid)
            {
                var newEntity = new Movie
                {
                    Tittel = movieViewModel.Tittel,           
                    Duurtijd = movieViewModel.Duurtijd,
                    MovieId = Guid.NewGuid(),
                    Release = movieViewModel.Release,
                    MovieImg = new MovieImg() { Id = ImgToUpload.Id, Path = ImgToUpload.Path },

                };
                movieEntities.Add(newEntity);
                _myDatabase.AddMovie(newEntity);
                ImgToUpload = null;
                return RedirectToAction("Index");
            }
            else if (movieImgEntities.Count != 0)
            {
                movieViewModel.MovieImg = new MovieImg() { Id = ImgToUpload.Id, Path = ImgToUpload.Path };
                ImgToUpload = null;
            }
            return View(movieViewModel);
        }
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult Detail()
        {
            MovieDetailViewModel mijnModel = new MovieDetailViewModel();
            string myvalue = Request.Form["LijstFilms"].ToString();
            if (myvalue == "")
                myvalue = Request.Form["Lijst"].ToString();
            if (myvalue != "")
            {
                foreach (Movie movie in movieEntities)
                {
                    if (movie.Tittel == myvalue)
                    {
                        mijnModel.MovieId = movie.MovieId;
                        mijnModel.Tittel = movie.Tittel;
                        mijnModel.Duurtijd = movie.Duurtijd;
                        mijnModel.Release = movie.Release;
                        mijnModel.MovieImg = movie.MovieImg;
                    }
                }
                return View(mijnModel);
            }          
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Detail(Guid sausissen)
        {
            
            var mymovie = movieEntities.FirstOrDefault(x => x.MovieId == sausissen);
            var movieDetailViewModel = new MovieDetailViewModel()
            {
                Tittel = mymovie.Tittel,
                MovieId = mymovie.MovieId,
                MovieImg = mymovie.MovieImg,
                Duurtijd = mymovie.Duurtijd,
                Release = mymovie.Release,
            };
            return View(movieDetailViewModel);
        }
        [HttpGet]
        public IActionResult CreateImg(MovieCreateViewModel model)
        {
            var isModelValid = TryValidateModel(model);
            MovieCreateViewModel thismodel = new MovieCreateViewModel();
            if (isModelValid)
            {
                thismodel.MovieImg = model.MovieImg;
                thismodel.MovieId = model.MovieId;
                thismodel.Tittel = model.Tittel;
                thismodel.Duurtijd = model.Duurtijd;
                thismodel.Release = model.Release;

            }
            return View(thismodel);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateImg(MovieImg image, IFormFile uploadFile)
        {           
            if (uploadFile != null && uploadFile.Length > 0)
            {
                var fileName = Path.GetFileName(uploadFile.FileName);

                var filePath = Path.Combine(@"wwwroot\Images\", fileName);
                string[] subbie = filePath.Split('\\');
                //"~/Images/angularmerkel.png"
                image.Id = Guid.NewGuid(); 
                image.Path = "~/" + subbie[1] + "/" + subbie[2];
                movieImgEntities.Add(image);
                _myDatabase.AddMovieImg(image);
                ImgToUpload = image;
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await uploadFile.CopyToAsync(fileStream);
                    
                }

            }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public IActionResult Update(Guid id)
        {
            MovieCreateViewModel movieCreateViewModel = new MovieCreateViewModel();
            foreach (var movie in movieEntities)
            {
                if (movie.MovieId == id)
                {
                    movieCreateViewModel.Tittel = movie.Tittel;
                    movieCreateViewModel.MovieImg = movie.MovieImg;
                    movieCreateViewModel.Duurtijd = movie.Duurtijd;
                    movieCreateViewModel.MovieId = id;
                    movieCreateViewModel.MovieScreenshots = movie.MovieScreenshots;
                    movieCreateViewModel.Release = movie.Release;
                    break;
                }
            }
            return View(movieCreateViewModel);
        }
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult Update(MovieCreateViewModel movieViewModel)
        {

            Movie mymovie = movieEntities.FirstOrDefault(x => x.MovieId == movieViewModel.MovieId);
            ImgToUpload = mymovie.MovieImg;
            movieEntities.Remove(movieEntities.FirstOrDefault(x => x.MovieId == movieViewModel.MovieId));
                var newEntity = new Movie
                {                   
                    
                    Tittel = movieViewModel.Tittel,
                    Duurtijd = movieViewModel.Duurtijd,
                    MovieId = movieViewModel.MovieId,
                    Release = movieViewModel.Release,
                    MovieImg = ImgToUpload,
                };
                movieEntities.Add(newEntity);
                _myDatabase.UpdateMovie(newEntity);
                return RedirectToAction("Index");           
        }
        [HttpGet]
        public IActionResult Delete(Guid id)
        {          
            var movie = movieEntities.FirstOrDefault(x => x.MovieId == id);
            MovieCreateViewModel movieCreateViewModel = new MovieCreateViewModel
            {
                Tittel = movie.Tittel,
                MovieId = movie.MovieId,
                MovieImg = movie.MovieImg,
                Duurtijd = movie.Duurtijd,
                Release = movie.Release,
            };
            return View(movieCreateViewModel);
        }
        public IActionResult DeleteConfirm(Guid id)
        {
            var movie = movieEntities.FirstOrDefault(x => x.MovieId == id);
            movieEntities.Remove(movie);
            _myDatabase.RemoveMovie(movie);
            return RedirectToAction("Index");
        }
      
        public IActionResult IndexSort(int filter)
        {
            Filter = filter;


            return RedirectToAction("Index");
        }
        
        public IActionResult SearchTitle(string search)
        {
             Search = search;

            return RedirectToAction("Index");
        }

        public IActionResult Forms()
        {          
            return View();
        }
    }
}

MovieWeb/Views/Customer/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CustomerCreateViewModel

<form asp-controller="Customer" asp-action="Create" method="post">
    @*Patroon*@
    <div class="form-group">
        <label asp-for="Naam"></label>
        <input class="form-control" asp-for="Naam"/>
        <span class="text-danger" asp-validation-for="Naam"></span>
    </div>
    @*Herhaal het patroon voor alle properties.*@
    <div class="form-group">
        <label asp-for="Voornaam"></label>
        <input class="form-control" asp-for="Voornaam"/>
        <span class="text-danger" asp-validation-for="Voornaam"></span>
    </div>
    <button class="btn btn-primary" type="submit">Add Customer</button>
</form>

MovieWeb/Views/Customer/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CustomerDeleteViewModel

<p>Bent u zeker dat u klant @Model.Naam wilt verwijderen?</p>

<form asp-controller="Customer" asp-action="DeleteConfirm" method="post">
    @*Patroon*@
    <input asp-for="CustomerId" type="hidden"/>
   
    <button class="btn btn-primary" type="submit">Delete Customer</button>
    
</form>

<a asp-controller="Movie" asp-action="Index">Ga terug!</a>

MovieWeb/Views/Customer/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CustomerDetailViewModel


<p>@Model.Voornaam @Model.Naam</p>

MovieWeb/Views/Customer/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CustomerEditViewModel

<form asp-controller="Customer" asp-action="Edit" method="post">
    @*Patroon*@
    <input asp-for="CustomerId" type="hidden"/>
    <div class="form-group">
        <label asp-for="Naam"></label>
        <input class="form-control" asp-for="Naam"/>
        <span class="text-danger" asp-validation-for="Naam"></span>
    </div>
    @*Herhaal het patroon voor alle properties.*@
    <div class="form-group">
        <label asp-for="Voornaam"></label>
        <input class="form-control" asp-for="Voornaam"/>
        <span class="text-danger" asp-validation-for="Voornaam"></span>
    </div>
    <button class="btn btn-primary" type="submit">Edit Customer</button>
</form>

MovieWeb/Views/Customer/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<CustomerListViewModel>


<div>
    <h1>Overzicht Customers:</h1>  
    <table>
            @foreach (var Customer in Model)
            {
                    <tr>
                        <td><a class="btn btn-primary" asp-action="Detail" asp-controller="Customer" asp-route-CustomerId=@Customer.CustomerId>@Customer.Voornaam @Customer.Naam</a></td>
                        <td><a class="btn btn-primary" asp-action="Edit" asp-controller="Customer" asp-route-CustomerId=@Customer.CustomerId>Edit</a></td>
                        <td><a class="btn btn-primary" asp-action="Delete" asp-controller="Customer" asp-route-CustomerId=@Customer.CustomerId>Delete</a></td>
                    </tr>                    
            }                                       
    </table>  
</div>
<div style="margin:20px;">
     <a class="btn btn-secondary" asp-action="Create" asp-controller="Customer" width="400px">Voeg Nieuwe Customer Toe</a>
</div>