MovieWeb/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Domain;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    public class StatisticsController : Controller
    {
        public static List<Uitgave> lijstUitgaven = new List<Uitgave>
        {
            new Uitgave() {ID = Guid.NewGuid(), Description = "original invoice", Date = DateTime.Now, Amount = 50}
        };

        public static int Filter = 0;
        [HttpGet]
        public IActionResult Index()
        {
            List<UitgaveDetailViewModel> lijstUitgave = new List<UitgaveDetailViewModel>();
            foreach (var item in lijstUitgaven)
            {
                lijstUitgave.Add(new UitgaveDetailViewModel()
                {
                    ID = item.ID,
                    Description = item.Description,
                    Date = item.Date,
                    Amount = item.Amount
                });
            }

            switch(Filter)
            {
                case 1:
                    lijstUitgave.OrderBy(x => x.Date);
                    break;
                case 2:
                    lijstUitgave.OrderByDescending(x => x.Amount);
                    break;
                case 3:
                    lijstUitgave.OrderBy(x => x.Amount);
                    break;
                default:
                    lijstUitgave.OrderByDescending(x => x.Date);
                    break;

            }
            return View(lijstUitgave);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult IndexSort(int filter)
        {
            Filter = filter;

        
            return RedirectToAction("Index");
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult IndexReset()
        {
            Filter = 0;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            var uitgaveEntity = new UitgaveDetailViewModel();
         
            return View(uitgaveEntity);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult Create(UitgaveDetailViewModel dmodel)
        {
            if(TryValidateModel(dmodel))
            {
                var newuitgave = new Uitgave
                {
                    ID = Guid.NewGuid(),
                    Description = dmodel.Description,
                    Amount = dmodel.Amount,
                    Date = dmodel.Date
                };
                lijstUitgaven.Add(newuitgave);
                return RedirectToAction("Index");
            }
            return View(dmodel);
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var y = lijstUitgaven.SingleOrDefault(x => x.ID == id);

            var dmodel = new UitgaveDetailViewModel
            {
                ID = y.ID,
                Description = y.Description,    
                Date = y.Date,
                Amount = y.Amount
            };
            return View(dmodel);
        }
        
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult Edit(Guid id, UitgaveDetailViewModel dmodel)
        {
            if(TryValidateModel(dmodel))
            {
                var y = lijstUitgaven.SingleOrDefault(x => x.ID == dmodel.ID);
                y.Description = dmodel.Description;
                y.Amount = dmodel.Amount;
                y.Date = dmodel.Date;
                
                return RedirectToAction("Index");
            }
            return View(dmodel);
        }
        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var y = lijstUitgaven.SingleOrDefault(x => x.ID == id);

            var dmodel = new UitgaveDeleteViewModel
            {
                ID = y.ID,
                Description = y.Description,
                Date = y.Date,
            };
            return View(dmodel);
        }
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult DeleteConfirm(Guid id)
        {

                var y = lijstUitgaven.Single(x => x.ID == id);
               lijstUitgaven.Remove(y);

                return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Statistics()
        {
            List<UitgaveDetailViewModel> lijstUitgave = new List<UitgaveDetailViewModel>();
            foreach (var item in lijstUitgaven)
            {
                lijstUitgave.Add(new UitgaveDetailViewModel()
                {
                    ID = item.ID,
                    Description = item.Description,
                    Date = item.Date,
                    Amount = item.Amount
                });
            }

            return View(lijstUitgave);
        }
    }
    
}

MovieWeb/Views/Statistics/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model UitgaveDetailViewModel

<h1>Add new Invoice</h1>
<form asp-controller="Statistics" asp-action="Create" method="post">
    @*Patroon*@
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    @*Herhaal het patroon voor alle properties.*@
    <div class="form-group">
        <label asp-for="Amount"></label>
        <input class="form-control" asp-for="Amount" />
        <span class="text-danger" asp-validation-for="Amount"></span>
    </div>
      <div class="form-group">
        <label asp-for="Date"></label>
        <input class="form-control" asp-for="Date" />
        <span class="text-danger" asp-validation-for="Date"></span>
    </div>  
        <button class="btn btn-primary" type="submit">Create Invoice</button>

    </form>

MovieWeb/Views/Statistics/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model UitgaveDeleteViewModel
@{
}
<p>@Model.Description</p>
<p>@Model.Date</p>

<p>Are you sure you want to delete this invoice?</p>
<form method="post" asp-action="DeleteConfirm" asp-controller="Statistics" asp-route-id=@Model.ID >
    <button type="submit">Yes</button>
</form>
<a class="button" asp-controller="Statistics" asp-action="Index" >No</a>

MovieWeb/Views/Statistics/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model UitgaveDetailViewModel

<h1>Add new Invoice</h1>
<form asp-controller="Statistics" asp-action="Edit" method="post" asp-route-id=@Model.ID>
    @*Patroon*@
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" value=@Model.Description/>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    @*Herhaal het patroon voor alle properties.*@
    <div class="form-group">
        <label asp-for="Amount"></label>
        <input class="form-control" asp-for="Amount" value=@Model.Amount/>
        <span class="text-danger" asp-validation-for="Amount"></span>
    </div>
      <div class="form-group">
        <label asp-for="Date"></label>
        <input class="form-control" asp-for="Date" value=@Model.Date/>
        <span class="text-danger" asp-validation-for="Date"></span>
    </div>  
        <button class="btn btn-primary" type="submit">Update Invoice</button>

    </form>

MovieWeb/Views/Statistics/Index.cshtml
@using MovieWeb.Controllers
@{
    string[] filters = new string[] { "Datum Aflopend", "Datum Oplopend", "Bedrag Aflopend", "Bedrag Oplopend" };
}
@model List<UitgaveDetailViewModel>
    <div class="form-box">
    <p>Sorteer op:</p>
    <div class="form">
 <form asp-action="IndexSort" asp-controller="Statistics" method="post">
          <select asp-for=@StatisticsController.Filter>
             @for(int i = 0; i <= 3; i++)
              {
                     <option value=@i>@filters[i]</option>
              }
            </select>
         <button class="btn btn-primary" type="submit">Sort</button>
</form>
</div>
<a class="btn btn-primary" asp-controller="Statistics" asp-action="Create">Maak Invoice Aan</a>
</div>
@if (@Model.Count != 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in @Model)
            {
                <tr>
                    <td>@x.Description</td>
                    <td><span>- @x.Amount</span></td>
                    <td>@x.Date</td>                          
                    <td><a class="btn btn-primary" asp-controller="Statistics" asp-action="Edit" asp-route-id="@x.ID">Edit</a></td>
                    <td><a class="btn btn-primary" asp-controller="Statistics" asp-action="Delete" asp-route-id="@x.ID">Delete</a></td>
                </tr>
            }
            
        </tbody>
    </table>
}
else
{
    <p>No invoices available!</p>
}

MovieWeb/Views/Statistics/Statistics.cshtml
@model List<UitgaveDetailViewModel>
@using MovieWeb.Controllers
@{
    var highestAmount = GetHighestAmount(Model);
    var lowestAmount = GetLowestAmount();
    var highestDate = GetHighestDate();
    var listByYearMonth = ExpensesByMonth();
}
@functions{
    UitgaveDetailViewModel GetHighestAmount(List<UitgaveDetailViewModel> list)
    {
        return list.OrderByDescending(x => x.Amount).ToList()[0];
    }
    UitgaveDetailViewModel GetLowestAmount()
    {
        return Model.OrderBy(x => x.Amount).ToList()[0];
    }
    UitgaveDetailViewModel GetHighestDate()
    {
        Model.OrderByDescending(x => x.Date).ToList();
        List<UitgaveDetailViewModel> listByDate = new List<UitgaveDetailViewModel>();

        for(int i = 0; i < Model.Count; i++)
        {
            if(i == 0)
            {
                listByDate.Add(Model[0]);
            }
            else
            {
                if(Model[i].Date.Date == listByDate[listByDate.Count -1].Date.Date)
                {
                    listByDate[listByDate.Count -1].Amount += Model[i].Amount;
                }
                else
                {
                    listByDate.Add(Model[i]);
                }
            }
        }
        return GetHighestAmount(listByDate);
    }
    List <UitgaveDetailViewModel> ExpensesByMonth()
    {
        Model.OrderByDescending(x => x.Date).ToList();
        List<UitgaveDetailViewModel> listByDate = new List<UitgaveDetailViewModel>();

        for(int i = 0; i < Model.Count; i++)
        {
            if(i == 0)
            {
                listByDate.Add(Model[0]);
            }
            else
            {
                if(Model[i].Date.Year == listByDate[listByDate.Count -1].Date.Year)
                {
                    if(Model[i].Date.Month == listByDate[listByDate.Count -1].Date.Month)
                    {
                        listByDate[listByDate.Count -1].Amount += Model[i].Amount;
                    }
                    else
                    {
                        listByDate.Add(Model[i]);
                    }   
                }
                else
                {
                    listByDate.Add(Model[i]);
                }
            }
        }
        return listByDate;
    }
}
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Amount</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
      <tr>
         <td>Highest Amount</td>
       	<td>@highestAmount.Description</td>
        <td><span> - @highestAmount.Amount</span></td>
        <td>@highestAmount.Date</td>                                 
	</tr>
     <tr>
         <td>Lowest Amount</td>
       	<td>@lowestAmount.Description</td>
        <td><span> - @lowestAmount.Amount</span></td>
        <td>@lowestAmount.Date</td>                                 
	</tr>
     <tr>
         <td>Highest Expenses/Day</td>
       	<td>N/A</td>
        <td><span> - @highestDate.Amount</span></td>
        <td>@highestDate.Date.Date</td>                                 
	</tr>
</tbody>
</table>
   
<table class="table">
  <thead>
    <tr>
      <th scope="col">Amount</th>
      <th scope="col">Month/Year</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      @foreach(var x in listByYearMonth)
            {
                <td><span>@x.Amount</span></td>
       	        <td>@x.Date.Month/@x.Date.Year</td>
            }
	</tr>
</tbody>
</table>
   