MovieWeb/Controllers/RentedByController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Database.Design;
using MovieWeb.Domain;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RentedByController : Controller
    {
        private IMovieDatabase _context;
        public static List<Customer> allCustomers = new List<Customer>();
        public static List<Movie> allMovies = new List<Movie>();
        public static List<RentedBy> rentedByEnteties;

        public RentedByController(IMovieDatabase context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            allCustomers = _context.GetCustomer();
            allMovies = _context.GetMovies();
            rentedByEnteties = _context.GetRentedBy();
        }
        public IActionResult Index()
        {
            List<RentedByListViewModel> RentedBys = new List<RentedByListViewModel>();


            foreach (var RentedBy in rentedByEnteties)
            {
                RentedBys.Add(new RentedByListViewModel() { RentedById = RentedBy.RentedById, Customer = _context.FindCustomerById(RentedBy.CustomerId), Movie = _context.FindMovieByID(RentedBy.MovieId) });
            }
            return View(RentedBys);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RentedByCreateViewModel RentedByCreateViewModel)
        {
            //Controleer of de parameter geldig is:
            var isModelValid = TryValidateModel(RentedByCreateViewModel);

            if (isModelValid)
            {
                var newEntity = new RentedBy
                {
                    RentedById = RentedByCreateViewModel.RentedById,
                    CustomerId = RentedByCreateViewModel.CustomerId,
                    MovieId = RentedByCreateViewModel.MovieId,
                };

                _context.AddRentedBy(newEntity);

                return RedirectToAction("Index");
            }
            return View(RentedByCreateViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var RentedByCreateViewModel = new RentedByCreateViewModel();



            return View(RentedByCreateViewModel);
        }


        [HttpGet]
        public IActionResult Detail(Guid RentedById)
        {
            //Movie selectedMovie = movieEntities.FirstOrDefault(x => x.Title == title);

            var selectedRentedBy = _context.FindRentedById(RentedById);
            RentedByDetailViewModel viewRentedBy = new RentedByDetailViewModel()
            {
                RentedById = selectedRentedBy.RentedById,
                Customer = _context.FindCustomerById(selectedRentedBy.CustomerId),
                Movie = _context.FindMovieByID(selectedRentedBy.MovieId),
            };
            return View(viewRentedBy);
        }


        [HttpGet]
        public IActionResult Edit(Guid RentedById)
        {
            var selectedRentedBy = _context.FindRentedById(RentedById);

            if (selectedRentedBy == null) return new NotFoundResult();

            var newRentedByEdit = new RentedByEditViewModel()
            {
                RentedById = selectedRentedBy.RentedById,
                CustomerId = selectedRentedBy.CustomerId,
                MovieId = selectedRentedBy.MovieId
            };

            return View(newRentedByEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid RentedById, [FromForm] RentedByEditViewModel newRentedByEdit)
        {
            var selectedRentedBy = _context.FindRentedById(newRentedByEdit.RentedById);

            var modelValid = TryValidateModel(newRentedByEdit);

            if (modelValid)
            {
                if (selectedRentedBy == null) return new NotFoundResult();

                selectedRentedBy.CustomerId = newRentedByEdit.CustomerId;
                selectedRentedBy.MovieId = newRentedByEdit.MovieId;

                _context.UpdateRentedBy(selectedRentedBy);

                return RedirectToAction("Index");
            }
            return View(newRentedByEdit);
        }

        [HttpGet]
        public IActionResult Delete(Guid RentedById)
        {
            var selectedRentedBy = _context.FindRentedById(RentedById);

            var newRentedByDelete = new RentedByDeleteViewModel()
            {
                RentedById = selectedRentedBy.RentedById,
                CustomerNaam = _context.FindCustomerById(selectedRentedBy.CustomerId).Naam,
                MovieNaam = _context.FindMovieByID(selectedRentedBy.MovieId).Tittel,

            };

            return View(newRentedByDelete);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(RentedByDeleteViewModel newRentedByDelete)
        {
           
            var selectedRentedBy = _context.FindRentedById(newRentedByDelete.RentedById);

            if (selectedRentedBy == null) return new NotFoundResult();

            _context.RemoveRentedBy(selectedRentedBy);

            return RedirectToAction("Index");
        }
    }
}

MovieWeb/Views/RentedBy/Create.cshtml
@using MovieWeb.Controllers
@using MovieWeb.Domain

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@functions{
    public string GetFullName(Customer customer)
    {
        return customer.Voornaam + " " + customer.Naam;
    }
}

@model RentedByCreateViewModel


<form asp-controller="RentedBy" asp-action="Create">

    <select asp-for="CustomerId" 
            asp-items="@(new SelectList(RentedByController.allCustomers, nameof(Customer.CustomerId), nameof(Customer.Naam)))">
        <option>Please select one</option>
    </select>

    <select asp-for="MovieId" 
            asp-items="@(new SelectList(RentedByController.allMovies, nameof(Movie.MovieId), nameof(Movie.Tittel)))">
        <option>Please select one</option>
    </select>

    <input type="submit"/>

</form>

MovieWeb/Views/RentedBy/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
 @model RentedByDeleteViewModel
    

<h1>@Model.CustomerNaam -- @Model.MovieNaam</h1>
<p>Wilt u deze film verwijderen?</p>

<form asp-controller="RentedBy" asp-action="DeleteConfirm" method="post">
    
    <input asp-for="RentedById" type="hidden"/>
   
    <button class="btn btn-primary" type="submit">Delete RentedBy</button>
    
    <a class="btn btn-primary" asp-controller="RentedBy" asp-action="Index" style="margin-left:10px;">Neen</a>
</form>
    

MovieWeb/Views/RentedBy/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model RentedByDetailViewModel

<p>@Model.Customer.Voornaam @Model.Customer.Naam @Model.Movie.Tittel</p>

MovieWeb/Views/RentedBy/Edit.cshtml
@using MovieWeb.Controllers
@using MovieWeb.Domain
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model RentedByEditViewModel


<form asp-controller="RentedBy" asp-action="Edit">

    <input asp-for="RentedById" type="hidden"/>
    
    <select asp-for="CustomerId" 
            asp-items="@(new SelectList(RentedByController.allCustomers, nameof(Customer.CustomerId), nameof(Customer.Naam), Model.CustomerId))">
        <option>Please select one</option>
    </select>

    <select asp-for="MovieId" 
            asp-items="@(new SelectList(RentedByController.allMovies, nameof(Movie.MovieId), nameof(Movie.Tittel)))">
        <option>Please select one</option>
    </select>

    <input type="submit"/>

</form>

MovieWeb/Views/RentedBy/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<RentedByListViewModel>

<div>
    <a class="btn btn-secondary" style="width:400px;" asp-action="Create" asp-controller="RentedBy">Voeg toe</a>            
    <h1>Overzicht RentedBy:</h1>   
    <table>
            <thead>
        <tr>
            <th>Naam</th>
            <th>Voornaam</th>
            <th>Film</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
        @foreach (var RentedBy in Model)
            {
                    <tr>
                        <td>@RentedBy.Customer.Voornaam </td>
                        <td>@RentedBy.Customer.Naam </td>
                        <td>@RentedBy.Movie.Tittel</td>
                        <td><a class = "btn btn-primary" asp-action="Detail" asp-controller="RentedBy" asp-route-RentedById=@RentedBy.RentedById>Detail</a></td>
                        <td><a class = "btn btn-primary"asp-action="Edit" asp-controller="RentedBy" asp-route-RentedById=@RentedBy.RentedById>Edit</a></td>
                        <td><a class = "btn btn-primary"asp-action="Delete" asp-controller="RentedBy" asp-route-RentedById=@RentedBy.RentedById>Delete</a></td>
                    </tr>                    
            }     
    </table>    
</div>