MovieWeb/Controllers/MovieNightController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieWeb.Database.Design;
using MovieWeb.Domain;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MovieNightController : Controller
    {
        private IMovieDatabase _context;
        public static List<Customer> allCustomers = new List<Customer>();
        public static List<Movie> allMovies = new List<Movie>();
        public static Customer customerToAdd;
        public static Movie movieToAdd;

        public MovieNightController(IMovieDatabase context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            allCustomers = _context.GetCustomer();
            allMovies = _context.GetMovies();
        }
        public IActionResult Index()
        {
            List<MovieNightCreateViewModel> MovieNights = new List<MovieNightCreateViewModel>();

            foreach (var MovieNight in _context.GetMovieNight())
            {
                MovieNights.Add(new MovieNightCreateViewModel() { MovieNightId = MovieNight.MovieNightId, Naam = MovieNight.Naam, Omschrijving = MovieNight.Omschrijving, AllCustomers = MovieNight.AllCustomers });
            }
            return View(MovieNights);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var movieNightCreateViewModel = new MovieNightCreateViewModel();

            return View(movieNightCreateViewModel);
        }
              

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MovieNightCreateViewModel MovieNightCreateViewModel)
        {
            
            var isModelValid = TryValidateModel(MovieNightCreateViewModel);

            if (isModelValid)
            {
                           
                
                
                    var newEntity = new MovieNight
                    {
                        MovieNightId = Guid.NewGuid(),
                        Naam = MovieNightCreateViewModel.Naam,
                        Omschrijving = MovieNightCreateViewModel.Omschrijving,
                        AllCustomers = new List<Customer>(),
                        AllMovies = new List<Movie>()
                    };
                    _context.AddMovieNight(newEntity);
                    return RedirectToAction("Index");
                 
            }
            return View(MovieNightCreateViewModel);
        }          
        [HttpGet]
        public IActionResult Detail(Guid MovieNightId)
        {           
            var selectedMovieNight = _context.FindMovieNightById(MovieNightId);
            MovieNightCreateViewModel viewMovieNight = new MovieNightCreateViewModel()
            {
                Naam = selectedMovieNight.Naam,
                
            };
            return View(viewMovieNight);
        }


        [HttpGet]
        public IActionResult Edit(Guid MovieNightId)
        {
            var selectedMovieNight = _context.FindMovieNightById(MovieNightId);

            if (selectedMovieNight == null) return new NotFoundResult();

            var newMovieNightEdit = new MovieNightCreateViewModel()
            {
                MovieNightId = selectedMovieNight.MovieNightId,
                Naam = selectedMovieNight.Naam,
                Omschrijving = selectedMovieNight.Omschrijving
                
                
            };
            if (selectedMovieNight.AllCustomers != null)
            {
                newMovieNightEdit.AllCustomers = selectedMovieNight.AllCustomers.ToList();
            }
            return View(newMovieNightEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid Id, [FromForm] MovieNightCreateViewModel newMovieNightEdit)
        {
            var selectedMovieNight = _context.FindMovieNightById(newMovieNightEdit.MovieNightId);

            if (selectedMovieNight == null) return new NotFoundResult();

            selectedMovieNight.Naam = newMovieNightEdit.Naam;
            

            _context.UpdateMovieNight(selectedMovieNight);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(Guid MovieNightId)
        {
            var selectedMovieNight = _context.FindMovieNightById(MovieNightId);

            var newMovieNightDelete = new MovieNightCreateViewModel()
            {
                MovieNightId = selectedMovieNight.MovieNightId,
                Naam = selectedMovieNight.Naam
            };

            return View(newMovieNightDelete);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(MovieCreateViewModel newMovieNightDelete)
        {           
            var selectedMovieNight = _context.FindMovieNightById(newMovieNightDelete.MovieId);

            if (selectedMovieNight == null) return new NotFoundResult();

            _context.RemoveMovieNight(selectedMovieNight);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult AddCustomer(Guid MovieNightId)
        {
            var selectedMovieNight = _context.FindMovieNightById(MovieNightId);
            var newMovieNightAddCustomer = new MovieNightCreateViewModel()
            {
                MovieNightId = selectedMovieNight.MovieNightId,
                Naam = selectedMovieNight.Naam,
                Omschrijving = selectedMovieNight.Omschrijving,
                
            };
            if (selectedMovieNight.AllCustomers != null)
            {
                newMovieNightAddCustomer.AllCustomers = selectedMovieNight.AllCustomers.ToList();
            }
            return View(newMovieNightAddCustomer);          
        }
        [HttpPost]
        public IActionResult AddCustomer(MovieNightCreateViewModel newMovieNightAddCustomer)
        {
            var selectedCustomer = _context.FindCustomerById(newMovieNightAddCustomer.CustomerToAdd.CustomerId);
            var selectedMovieNight = _context.FindMovieNightById(newMovieNightAddCustomer.MovieNightId);
            if (selectedCustomer == null) return new NotFoundResult();
            if(selectedMovieNight.AllCustomers == null)
            {
                selectedMovieNight.AllCustomers = new List<Customer>();
            }
            selectedMovieNight.AllCustomers.Add(selectedCustomer);
           _context.UpdateMovieNight(selectedMovieNight);
            return RedirectToAction("Index");
        }
    }
}

MovieWeb/Views/MovieNight/AddCustomer.cshtml
@using MovieWeb.Controllers
@using MovieWeb.Domain
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MovieNightCreateViewModel

<form asp-controller="MovieNight" asp-action="AddCustomer" method="post"> 

    
        <label asp-for="MovieNightId" hidden="hidden"></label>
        <input asp-for="MovieNightId" hidden="hidden"/>
        
    
    <select asp-for="CustomerToAdd.CustomerId" 
            asp-items="@(new SelectList(@MovieNightController.allCustomers, nameof(Customer.CustomerId), nameof(Customer.Naam)))">
        <option>Please select one</option>
    </select>
    <input type="submit"/>

</form>

MovieWeb/Views/MovieNight/Create.cshtml
@using MovieWeb.Controllers
@using MovieWeb.Domain

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model MovieNightCreateViewModel


    <h1>Stap 1 :</h1>
    <form asp-controller="MovieNight" asp-action="Create" method="post">
    
    <div class="form-group">
        <label asp-for="Naam"></label>
        <input class="form-control" asp-for="Naam"/>
        <span class="text-danger" asp-validation-for="Naam"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="Omschrijving"></label>
        <input class="form-control" asp-for="Omschrijving"/>
        <span class="text-danger" asp-validation-for="Omschrijving"></span>
    </div>
    <button class="btn btn-primary" type="submit">Add MovieNight</button>
    </form>


    

MovieWeb/Views/MovieNight/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<MovieNightCreateViewModel>

<div>
    <h1>Overzicht MovieNights:</h1>
    

    <table>
           <thead>
        <tr>
            <th>Naam</th>
            <th>Aantal Customers</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
            @foreach (var MovieNight in Model)
            {
                    <tr>
                        <td>@MovieNight.Naam </td> 
                        
                        <td>
                            @if(MovieNight.AllCustomers != null)
                            {
                                @MovieNight.AllCustomers.Count
                            }
                    
                        </td>
                        <td><a class="btn btn-primary" asp-action="AddMovie" asp-controller="MovieNight" asp-route-MovieNightId=@MovieNight.MovieNightId>Add Movie</a></td>
                        <td><a class="btn btn-primary" asp-action="AddCustomer" asp-controller="MovieNight" asp-route-MovieNightId=@MovieNight.MovieNightId>Add Customer</a></td>
                        <td><a class="btn btn-secondary" asp-action="Edit" asp-controller="MovieNight" asp-route-MovieNightId=@MovieNight.MovieNightId>Edit</a></td>
                        <td><a class="btn btn-secondary" asp-action="Delete" asp-controller="MovieNight" asp-route-MovieNightId=@MovieNight.MovieNightId>Delete</a></td>
                    </tr>
                    
            }

            <tr>
                <a asp-action="Create" asp-controller="MovieNight">Voeg toe</a>
            </tr>
        </tbody>
    </table>
    

</div>
 @foreach (var x in Model)
    {
        if (x.AllCustomers != null)
        {
            <p>@x.Naam</p>
            @foreach (var customer in x.AllCustomers)
            {
            <p>@customer.Naam</p>
            }
        }
        
    }